sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

postgresql: &postgresql
  adapter: postgresql
  database: cp2mpoll_production
  username: cp2mpoll
  password: <%= ENV['CP2MPOLL_DATABASE_PASSWORD'] %>
#  database: <%=ENV['OPENSHIFT_APP_NAME']%>
#  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
#  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
#  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
#  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
#  min_messages: ERROR
#  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *defaults
  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>

test: &test
  <<: *defaults

production:
  <<: *defaults
  <<: *<%= ENV['RAILS_DB'] || "postgresql" %>
